name = "lucasilverentand-com"
account_id = "029d254cac84938ccede0b57a8711f31"
compatibility_date = "2026-04-10"

[build]
command = "bun install && bun run build"

[[routes]]
pattern = "lucasilverentand.com"
custom_domain = true

[[routes]]
pattern = "www.lucasilverentand.com"
custom_domain = true

[assets]
directory = "./dist"
